version: "3.8"

services:
  app:
    container_name: app
    build: .
    volumes:
      - ./logs:/logs
      - ./secrets:/secrets
      - ./data:/app/data  # Директория для хранения файла базы данных SQLite
    ports:
      - "3000:3000"
    environment:
      # Можете указать другие переменные окружения, необходимые вашему приложению
      NOTE_DBFILE: /app/data/db.sqlite  # Путь к файлу базы данных SQLite внутри контейнера
    restart: unless-stopped

volumes:
  # Создание тома для хранения данных SQLite
  data:
